### ISSUE TITLE
Async version of Connection does not use retry mechanism

### ISSUE THREAD

**Issue by szumka** [redis/redis-py#2211] opened 2022-06-02 14:05 UTC
**Version**: redis-py: 4.3.1

**Description**: Missing `call_with_retry` mechanism in async version of Connection (and SentinelManagedConnection). This behavior differs from the sync version of those classes. 

test to reproduce the issue:
```
import socket

import pytest

from redis.asyncio.retry import Retry
from redis.asyncio.sentinel import SentinelManagedConnection
from redis.backoff import NoBackoff

from .compat import mock

pytestmark = pytest.mark.asyncio


async def test_connect_retry_on_timeout_error():
    """Test that the _connect function is retried in case of a timeout"""
    connection_pool = mock.AsyncMock()
    connection_pool.get_master_address = mock.AsyncMock(return_value=("localhost", 6379))
    conn = SentinelManagedConnection(retry_on_timeout=True, retry=Retry(NoBackoff(), 3), connection_pool=connection_pool)
    origin_connect = conn._connect
    conn._connect = mock.AsyncMock()

    async def mock_connect():
        # connect only on the last retry
        if conn._connect.call_count <= 2:
            raise socket.timeout
        else:
            return await origin_connect()

    conn._connect.side_effect = mock_connect
    await conn.connect()
    assert conn._connect.call_count == 3
```

**Comment by dvora-h** [comment] 2022-06-23 22:42
@szumka Is this issue still relevant or #2180 fixes it?

**Comment by dev-szukalski** [comment] 2022-06-24 11:42
@dvora-h The same issue still ocured - reproduced on the newest version of redis-py (commit 63cf7ec5cbaca533b7607196dbf993917a65c0f9)

**Comment by szumka** [comment] 2022-06-24 11:42
@dvora-h  The same issue still ocured - reproduced on the newest version of redis-py (commit https://github.com/redis/redis-py/commit/63cf7ec5cbaca533b7607196dbf993917a65c0f9)

**Comment by jonathansp** [comment] 2022-07-07 18:28
Still happening in 4.3.4

```python
  File "...python3.9/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
  File "...python3.9/site-packages/redis/asyncio/client.py", line 462, in _send_command_parse_response
    await conn.send_command(*args)
  File "...python3.9/site-packages/redis/asyncio/connection.py", line 905, in send_command
    await self.send_packed_command(
  File ".../site-packages/redis/asyncio/connection.py", line 896, in send_packed_command
    raise ConnectionError(...

redis.exceptions.ConnectionError: Error UNKNOWN while writing to socket. Connection lost.
```

**Comment by dvora-h** [comment] 2022-07-21 12:15
Closed because it was fixed in # 2271

**Closed by dvora-h** 2022-07-21 12:15 UTC
