### ISSUE TITLE
Seeking guidance for `hiredis` dependency on `redis-py`

### ISSUE THREAD

**Issue by ramchandra-st** [redis/redis-py#3392] opened 2024-09-29 15:15 UTC
I have a question regarding the `hiredis` dependency in `redis-py`. 
Is hiredis a required dependency for using the package, or is it optional? 

I have an implicit dependency on `redis-py`  and I've encountered an issue with a locked version of `hiredis` in my `requirements.txt`

Since `redis-py` updates automatically as it is implicit, it can lead to a version mismatch where `redis-py` is updated, but `hiredis` remains locked to an older version, causing an unsynchronized state.

Could you provide guidance on how to handle this situation and avoid any conflicts arising from the version lock?

**Comment by ramchandra-st** [comment] 2024-09-29 15:25
I see in recent `redis-py` update (5.0.1), author have forget to mention hiredis depedeny although I see it mention [here](https://github.com/redis/redis-py/pull/3324#issue-2419053541:~:text=Upgrade%20the%20required%20hiredis%2Dpy%20version%20to%20be%20at%20least%203.0.0): 

I think mentioning such changlog in release log would be quite helpful for other developers.

**Comment by ramchandra-st** [comment] 2024-09-29 15:28
So I request to add this information on release notes of 5.1.0 :)

**Comment by dmaier-redislabs** [comment] 2024-09-30 13:17
Hi @ramchandra-st,

it's possible to use `redis-py` without `hiredis`, but if `hiredis` is installed, then `redis-py` will use it. This is documented in the README here on Github.

Which version of `hiredis` are you using?

Regards,
David

**Comment by helissonomc** [comment] 2024-09-30 15:09
Hey guys, i created this issue https://github.com/redis/redis-py/issues/3393 about it, i just realised that this is talking about this same issue, should i close it?

**Comment by dmaier-redislabs** [comment] 2024-09-30 17:17
@helissonomc Yes, please. Can you add any relevant detail here please.

**Comment by helissonomc** [comment] 2024-09-30 19:39
With version 5.1.0 the introduced issue is the code inside redis/utils.py
```
try:
    import hiredis  # noqa

    # Only support Hiredis >= 3.0:
    HIREDIS_AVAILABLE = int(hiredis.__version__.split(".")[0]) >= 3
    HIREDIS_PACK_AVAILABLE = hasattr(hiredis, "pack_command")
except ImportError:
    HIREDIS_AVAILABLE = False
    HIREDIS_PACK_AVAILABLE = False
   ```
If the hiredis version is lower than 3 (which mine is) the HIREDIS_AVAILABLE is going to be false, therefore it will keep giving error inside the redis/connection.py file, because the import hiredis will not be executed, but the code still relies on this import.

**Comment by ramchandra-st** [comment] 2024-10-01 07:55
Yeah, problem @helissonomc is same as what I want to highlight here.

Thanks folks for engagement here :)

**Comment by dmaier-redislabs** [comment] 2024-10-01 09:09
OK, seems to be a bug that was introduced by trying to enforce hiredis >=3. We will take a look and fix it. Thanks for the detailed report.

**Comment by dmaier-redislabs** [comment] 2024-10-02 12:30
Hi,

this bug could be reproduced with `redis-py` 5.1.0 and `hiredis-py` 2.4.0. The library `redis-py' should fall back to it's internal response parser if the `hiredis-py` has a lower version than 3.0. There are two Boolean variables checked and `HIREDIS_PACK_AVAILABLE` can be true if any version is installed, which causes the bug. This will be fixed in a maintenance version. We apologize for the inconvenience.

Regards,
David

**Closed** 2024-10-04 13:03 UTC
Labels: bug
