### ISSUE TITLE
4.2.2 breaks some stuff on python 3.7

### ISSUE THREAD

**Issue by osallou** [redis/redis-py#2156] opened 2022-04-30 05:46 UTC
**Version**: What redis-py and what redis version is the issue happening on?

4.2.2

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Debian buster , python 3.7.3

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

After pip3 install of redis, something is broken and many packages fail to install (while install is ok before redis install)

** Reproduce **

In docker:

    docker run -it --rm debian:buster /bin/bash
    apt-get update && apt-get install -y python3-pip

Steps: install gunicorn (ok), uninstall gunicorn, install redis (ok), install gunicorn (ko)

    root@4b670aedfc3a:/# pip3 install gunicorn
    Collecting gunicorn
    Downloading https://files.pythonhosted.org/packages/e4/dd/5b190393e6066286773a67dfcc2f9492058e9b57c4867a95f1ba5caf0a83/gunicorn-20.1.0-py3-none-any.whl (79kB)
        100% |████████████████████████████████| 81kB 1.7MB/s 
    Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn) (40.8.0)
    Installing collected packages: gunicorn
    Successfully installed gunicorn-20.1.0
    root@4b670aedfc3a:/# pip3 uninstall gunicorn
    Uninstalling gunicorn-20.1.0:
    Would remove:
        /usr/local/bin/gunicorn
        /usr/local/lib/python3.7/dist-packages/gunicorn-20.1.0.dist-info/*
        /usr/local/lib/python3.7/dist-packages/gunicorn/*
    Proceed (y/n)? y
    Successfully uninstalled gunicorn-20.1.0
    root@4b670aedfc3a:/# pip3 install redis   
    Collecting redis
    Downloading https://files.pythonhosted.org/packages/d3/2d/1aefc345181d53d618b48f7c2bdc491a6ec4f2be1923c37e04536ef2f9c4/redis-4.2.2-py3-none-any.whl (226kB)
        100% |████████████████████████████████| 235kB 2.3MB/s 
    Collecting async-timeout>=4.0.2 (from redis)
    Downloading https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl
    Collecting importlib-metadata>=1.0; python_version < "3.8" (from redis)
    Downloading https://files.pythonhosted.org/packages/92/f2/c48787ca7d1e20daa185e1b6b2d4e16acd2fb5e0320bc50ffc89b91fa4d7/importlib_metadata-4.11.3-py3-none-any.whl
    Collecting typing-extensions; python_version < "3.8" (from redis)
    Downloading https://files.pythonhosted.org/packages/75/e1/932e06004039dd670c9d5e1df0cd606bf46e29a28e65d5bb28e894ea29c9/typing_extensions-4.2.0-py3-none-any.whl
    Collecting deprecated>=1.2.3 (from redis)
    Downloading https://files.pythonhosted.org/packages/51/6a/c3a0408646408f7283b7bc550c30a32cc791181ec4618592eec13e066ce3/Deprecated-1.2.13-py2.py3-none-any.whl
    Collecting packaging>=20.4 (from redis)
    Downloading https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40kB)
        100% |████████████████████████████████| 40kB 129kB/s 
    Collecting zipp>=0.5 (from importlib-metadata>=1.0; python_version < "3.8"->redis)
    Downloading https://files.pythonhosted.org/packages/80/0e/16a7ee38617aab6a624e95948d314097cc2669edae9b02ded53309941cfc/zipp-3.8.0-py3-none-any.whl
    Collecting wrapt<2,>=1.10 (from deprecated>=1.2.3->redis)
    Downloading https://files.pythonhosted.org/packages/00/11/e69d554d32900f42fc7d3ebb5d3132b1756d29f8a1f85ebf1de720d890da/wrapt-1.14.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (75kB)
        100% |████████████████████████████████| 81kB 4.2MB/s 
    Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging>=20.4->redis)
    Downloading https://files.pythonhosted.org/packages/d9/41/d9cfb4410589805cd787f8a82cddd13142d9bf7449d12adf2d05a4a7d633/pyparsing-3.0.8-py3-none-any.whl (98kB)
        100% |████████████████████████████████| 102kB 5.7MB/s 
    Installing collected packages: typing-extensions, async-timeout, zipp, importlib-metadata, wrapt, deprecated, pyparsing, packaging, redis
    Successfully installed async-timeout-4.0.2 deprecated-1.2.13 importlib-metadata-4.11.3 packaging-21.3 pyparsing-3.0.8 redis-4.2.2 typing-extensions-4.2.0 wrapt-1.14.0 zipp-3.8.0
    root@4b670aedfc3a:/# pip3 install gunicorn
    Collecting gunicorn
    Exception:
    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
        status = self.run(options, args)
    File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
        resolver.resolve(requirement_set)
    File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
        self._resolve_one(requirement_set, req)
    File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
        self.require_hashes
    File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
        req.populate_link(finder, upgrade_allowed, require_hashes)
    File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
        self.link = finder.find_requirement(self, upgrade)
    File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 572, in find_requirement
        all_candidates = self.find_all_candidates(req.name)
    File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 534, in find_all_candidates
        self._package_versions(page.iter_links(), search)
    File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 702, in _package_versions
        v = self._link_package_versions(link, search)
    File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 777, in _link_package_versions
        support_this_python = check_requires_python(link.requires_python)
    File "/usr/lib/python3/dist-packages/pip/_internal/utils/packaging.py", line 33, in check_requires_python
        return python_version in requires_python_specifier
    File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 676, in __contains__
        return self.contains(item)
    File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 681, in contains
        item = parse(item)
    File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 28, in parse
        return Version(version)
    File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 219, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    
This error occurs with many packages after redis installation.

Installing redis 3.5.3 presents no issue.

Installating redis on python 3.10 (my computer) has no issue

    root@4b670aedfc3a:/# pip3 list
    Package            Version
    ------------------ -------
    asn1crypto         0.24.0 
    async-timeout      4.0.2  
    cryptography       2.6.1  
    Deprecated         1.2.13 
    entrypoints        0.3    
    importlib-metadata 4.11.3 
    keyring            17.1.1 
    keyrings.alt       3.1.1  
    packaging          21.3   
    pip                18.1   
    pycrypto           2.6.1  
    PyGObject          3.30.4 
    pyparsing          3.0.8  
    pyxdg              0.25   
    redis              4.2.2  
    SecretStorage      2.3.1  
    setuptools         40.8.0 
    six                1.12.0 
    typing-extensions  4.2.0  
    wheel              0.32.3 
    wrapt              1.14.0 
    zipp               3.8.0

**Comment by chayim** [comment] 2022-05-04 06:59
@osallou I notice that first you install gunicorn - and that dist-packages are involved in your environment. Can you run this cleanly on a clean python3.7 virtualenv? This is how we currently test - in order to avoid the potential for system issues.

**Comment by osallou** [comment] 2022-05-04 07:18
Hi, same in a venv

    python3 -mvenv venv
    venv/bin/activate
    pip3 install gunicorn => OK
    pip3 uninstall gunicorn => OK
    pip3 install redis => OK
    pip3 install gunicorn  => KO
    ...
    Installing collected packages: pyparsing, packaging, typing-extensions, async-timeout, wrapt, deprecated, zipp, importlib-metadata, redis
    Successfully installed async-timeout-4.0.2 deprecated-1.2.13 importlib-metadata-4.11.3 packaging-21.3 pyparsing-3.0.8 redis-4.2.2 typing-extensions-4.2.0 wrapt-1.14.1 zipp-3.8.0
    (venv) root@4a1a50f32cdf:~# pip3 install gunicorn
    Collecting gunicorn
    Exception:
    Traceback (most recent call last):
      File "/root/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
        status = self.run(options, args)
      File "/root/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 338, in run
    ...
      File "/root/venv/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 219, in __init__
    match = self._regex.search(version)
    TypeError: expected string or bytes-like object

**Comment by agronholm** [comment] 2022-05-05 09:15
Shouldn't you report this to gunicorn devs, as this seems to have nothing whatsoever to do with this project?

**Comment by osallou** [comment] 2022-05-05 09:35
This error occurd with multiple packages, not gunicorn only, and only after redis package install

**Comment by chayim** [comment] 2022-05-09 05:46
@osallou It looks like you're having a dependency issue with another package. What happens if you install only redis-py. In a clean venv, I expect this to work. That would point to a dependency issue.

Can you use a dependency tool such as poetry to reproduce?  I've run the following in a fresh docker - with no issues - so I'm a bit flummoxed:

```
docker run -it debian:buster bash
apt update && apt install -y python3-pip
pip3 install redis
```

Now redis

```
root@07a10b2ee317:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@07a10b2ee317:/# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> r = redis.Redis()
>>> r.ping()
True
```

**Comment by osallou** [comment] 2022-05-09 05:53
Redis install itself works.

The problem is the installation of different other packages after redis install (gunicorn and others), while there is no issue if i do not install redis. As if redis breaks something needed for some other package installation.

**Comment by chayim** [comment] 2022-05-11 11:35
Redis has it's own requirements - as do each package. One of the reasons behind tools such as [poetry](https://python-poetry.org). is to address this collection of problems.  It's not the role of redis-py to solve this issue, as it defines its depenencies, the same as any other library.

This is best left to the user. Closing.

**Closed by chayim** 2022-05-11 11:35 UTC

**Comment by MarioCavero** [comment] 2022-08-05 11:16
> Redis install itself works.
> 
> The problem is the installation of different other packages after redis install (gunicorn and others), while there is no issue if i do not install redis. As if redis breaks something needed for some other package installation.

@osallou 
I was having the same issue after installing several pip packages, until I realized it was after installing redis, that pip packaging was breaking. What's really happening is that the packaging version changes ([check this issue in pip](https://github.com/pypa/pip/issues/11343#issuecomment-1204374208)), FOR SOME REASON due to broken pip installation (or pip3 install redis) breaking it, or something related to the distribution.
